name: Release Instant Seal Node With Deployed Schemas Docker Image
on:
  push:
    tags: '*'

jobs:
  docker-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the tag name
        run: |
          echo ${{ github.ref_name }}
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build and push dsnp/instant-seal-node-with-deployed-schemas
        id: docker_build_instant_seal_node_with_deployed_schemas
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: |
            dsnp/instant-seal-node-with-deployed-schemas:${{ env.TAG }}


      - name: Image digests
        run: |
          echo dsnp/instant-seal-node-with-deployed-schemas ${{ steps.docker_build_instant_seal_node_with_deployed_schemas.outputs.digest }}
