name: Release Instant Seal Node With Deployed Schemas Docker Image
on:
  push:
    tags: [ docker/* ]

jobs:
  docker-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the tag name
        run: |
          echo ${GITHUB_REF##*/}
          echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push dsnp/instant-seal-node-with-deployed-schemas
        id: docker_build_instant_seal_node_with_deployed_schemas
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: |
            dsnp/instant-seal-node-with-deployed-schemas:${{ env.TAG }}
            dsnp/instant-seal-node-with-deployed-schemas:latest


      - name: Image digests
        run: |
          echo dsnp/instant-seal-node-with-deployed-schemas ${{ steps.docker_build_instant_seal_node_with_deployed_schemas.outputs.digest }}
