name: Tests CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: package-lock.json

      - name: Install 💾
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish Dry Run
        run: npm publish --dry-run
        working-directory: dist
